Name=input("Enter your name: ")
Age=int(input("Enter your age: "))
Course=input("Enter your course: ")
College=input("Enter your college name: ")
Email=input("Enter your email: ")
Phone=int(input("Enter your phone number: "))
City=input("Enter your city: ")
print(f"==============================\n\tSTUDENT PROFILE\n==============================")
print(f"Name : {Name}\nAge : {Age}\nCourse : {Course}\nCollege : {College}\nEmail : {Email}\nPhone : {Phone}\nCity : {City}\n")
print("==============================")