Name=input("Enter your name: ")
Age=int(input("Enter your age: "))
City=input("Enter your city: ")
College=input("Enter your college: ")
print("\n----- Student Information -----\n\nName    : ", Name ,"\nAge     : ",Age,"\nCity    ",City,"\nCollege : ",College)
# print("Name    : ", Name)
# print("Age     : ", Age)
# print("City    : ", City)
# print("College : ", College)