import numpy as np
Match_Runs= np.random.randint(1,100,14)
Runs_Conceded=np.random.randint(1,100,14)
print("-"*50)
print("Match_Runs :")
print(Match_Runs)
print("-"*50)
print("Runs_Conceded :")
print(Runs_Conceded)
print("-"*50)
print(f"Highest Score   : {Match_Runs.max()}")
print("-"*50)
print(f"Lowest Score   : {Match_Runs.min()}")
print("-"*50)
print(f"Average Score   : {Match_Runs.mean()}")
print("-"*50)
print("Net Run Difference (Runs Scored − Runs Conceded) : \n")
print(f"{Match_Runs-Runs_Conceded}")
print("-"*50)
print("Matches where team scored above average")
print(f" Index of Matches {1+np.where(Match_Runs>Match_Runs.mean())[0]}")
print("-"*50)