Name=input("Enter your name: ")
Age=int(input("Enter your age: "))
Course=input('Enter your course: ')
College=input('Enter your college: ')
City=input('Enter your city: ')
Phone_Number=int(input('Enter your phone number: '))
print("====================================\n")
print("        STUDENT ID CARD\n")
print("====================================\n\n")
print("Name      : ",Name,"\nAge       : ",Age,"\nCourse    : ",Course,"\nCollege   : ",College,"\nCity      : ",City,"\nPhone     : ",Phone_Number)
print("====================================\n\n")