import numpy as np
Seat_Numbers=np.arange(1,101)
print("\nThe  Array is :\n")
print(Seat_Numbers)
New_Seat_Numbers=Seat_Numbers.reshape(10,10)
print("-"*50)
print("The New Arranged Array is :\n")
print(New_Seat_Numbers)
print("-"*50)
print("The First Row of Arranged Array is :\n")
print(New_Seat_Numbers[0])
print("-"*50)
print("The Last Row of Arranged Array is :\n")
print(New_Seat_Numbers[-1])
