import numpy as np
Marks=np.random.randint(30,100,50)
print("-"*50)
print(f"Marks Array of Students:\n{Marks}")
print("-"*50)
print(f"Average Marks Of Whole Class : {Marks.mean()}")
print("-"*50)
print(f"Median Marks Of Whole Class : {np.median(Marks)}")
print("-"*50)
print(f"Standard Deviation in  Marks Of Students : {np.std(Marks)}")
print("-"*50)
print(f" ID of Student Above Average Marks : {Marks[Marks<Marks.mean()]}")
print("-"*50)
print(f"ID of Student Above below Average Marks: {Marks[Marks<Marks.mean()]}")
