Name=input("Enter Name :")
Age=int(input("Enter Age :"))
Course=input("Enter Course :")
College=input("Enter College :")
City=input("Enter City :")
Mobile=int(input("Enter Mobile :"))
Email=input("Enter Email :")
LinkedIn_Username=input("Enter LinkedIn Username :")
print("\n==================================================\n\t\tMY DIGITAL PROFILE\n==================================================\n\n")
print(f"Name\t\t: {Name}\nAge\t\t: {Age}\nCourse\t\t: {Course}\nCollege\t\t: {College}\nCity\t\t: {City}\nPhone\t\t: +91 {Mobile}\nEmai\t\t: {Email}\nLinkedIn\t: {LinkedIn_Username}")
print("==================================================\n\tThank You For Visiting My Profile\n==================================================\n\n")
