Name=input("Enter your name: ")
Age=int(input("Enter your age: "))
Qualification=input("Enter your qualification: ")
Skills=input("Enter your skills: ")
Experience=int(input("Enter your experience in years: "))
City=input("Enter your city: ")
Email=input("Enter your email: ")
print(f"==============================\n\tEMPLOYEE PROFILE\n==============================")
print(f"Name : {Name}\nAge : {Age}\nQualification : {Qualification}\nSkills : {Skills}\nExperience : {Experience} years\nCity : {City}\nEmail : {Email}\n")