import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# Number=int(input("Enter the No. of players You Want to enter the data :"))
# with open("ipl_stats.csv","w",newline="") as file:
#     writer=csv.writer(file)
#     writer.writerow(["Player Name","Team","Matches","Runs", "Strike Rate"])
#     for i in range(Number):
#         print("-"*50)
#         Player_Name=str(input(f"Enter The Name of Player {i+1} : "))
#         Team=str(input(f"Enter the {Player_Name} Team  Name : "))                                 # upper() not working 
#         Matches=int(input(f"Enter the Number of Matches Played by {Player_Name} : "))
#         Runs=int(input(f"Enter the Number of Runs Scored By {Player_Name} : "))
#         Strike_Rate=int(input(f"Enter The Strike Rate by {Player_Name} : "))
#         writer.writerow([Player_Name.upper(),Team.upper(),Matches,Runs,Strike_Rate])
# print("Exporting The Data To File Is Sucessfull")
print("-"*50)
print("Printing the Information Of players")
df_csv=pd.read_csv("ipl_stats.csv") 
print(df_csv)
print("-"*50)
print("Top 5 players by runs :")
print(df_csv.sort_values(by="Runs",ascending=False).head(5))
print("-"*50)
print("Players with Strike Rate > 140 :")
print(df_csv[df_csv["Strike Rate"]>150])
print("-"*50)
print("Average runs scored.")
print(df_csv["Runs"].mean())
print("-"*50)
print("Player with maximum runs are :")
print(df_csv["Runs"].max())
print("-"*50)
plt.figure(figsize=(12,6))
plt.subplot(2,2,1)
plt.bar(df_csv["Player Name"], df_csv["Runs"])
plt.xlabel("Player")
plt.ylabel("Runs")
plt.title("Bar Chart → Player vs Runs")
plt.grid(True)
plt.subplot(2,2,2)
plt.plot(df_csv["Matches"],df_csv["Runs"],color="blue",linestyle=" ",linewidth=2,marker="o",markersize=6)
plt.xlabel("Matches")
plt.ylabel("Runs")
plt.title("Scatter Plot → Matches vs Runs")
plt.grid(True)
plt.subplot(2,2,3)
plt.hist(df_csv["Strike Rate"],bins="auto")
plt.xlabel("Strike Rate")
plt.title("Histogram → Strike Rate Distribution")
plt.grid(True)
plt.tight_layout()
plt.show()
