import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("Hospital_Management.csv")
print(df.isnull().sum())
df=df.dropna()
df=df.drop_duplicates()
df["Amount"]=df["Amount"].abs()
df.to_csv("Hospital_Management.csv",index=False)
print("Depatment Generating Highest Revenue :")
print(((df.groupby("Department")["Amount"].sum()).sort_values(ascending=False).head(1)))
print("Dr Treating max Paitents :")
print((df["Doctor"].value_counts()).sort_values(ascending=False).head(1))
print("Average bill by Department")
print((df.groupby("Department")["Amount"].mean()).sort_values(ascending=False))
print("City Contributing the highest Revenue")
print((df.groupby("City")["Amount"].sum()).sort_values(ascending=False).head(1))

plt.figure(figsize=(12,6))
plt.subplot(2,2,1)
bar_graph=df.groupby("Department")["Amount"].sum()
plt.bar(bar_graph.index,bar_graph)
plt.title("Bar chart → Revenue by Department.")
plt.subplot(2,2,2)
Pie_chart=df["Department"].value_counts()
plt.pie(Pie_chart,labels=Pie_chart.index,autopct="%1.1f%%")
plt.title("Pie chart → Patients by Department..")
plt.subplot(2,2,3)
plt.hist(df["Amount"],bins="auto")
plt.title("Histogram → Bill Amount.")
plt.tight_layout()
plt.show()
#neurology department generates high revenue
#highly Visited Department by paitents is dermatology
#least revenue generated by orhopedics due to least no of paitent visit
# Major no of paitent pay    around 40,000-50,000
#less no of paitent pay around 10000-20000