import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("employee_performance.csv")
print("-"*70)
print(df)
print("-"*70)
print(df.info())
print("-"*70)
print(df.describe())
df["Salary"]=df["Salary"].fillna(df["Salary"].mean())
df["Performance"]=df["Performance"].fillna(df["Performance"].mean())
df["Experience"]=df["Experience"].fillna(df["Experience"].mean())
print(df.isnull())
print("-"*70)
print(df.duplicated())
df=df.drop_duplicates()
df.to_csv("employee_performance.csv",index=False)
print("-"*70)
print(df.duplicated().sum())
print("-"*70)
print("Average Salary is ")
print(df.groupby("Department")["Salary"].mean())
print("-"*70)
print("Highest performance rating : ")
print((df.groupby("City")["Performance"].mean()).sort_values(ascending=False))
print("-"*70)
print("Top Highest Paid Employee  is ")
print(df.sort_values(by="Salary",ascending=False)[["Employee ID", "Name", "Department", "City", "Salary"]].head(5))
plt.figure(figsize=(12,6))
plt.subplot(1,3,1)
Bar_Chart=df.groupby("Department")["Salary"].mean()
plt.bar(Bar_Chart.index,Bar_Chart)
plt.xlabel("Depatment")
plt.ylabel("Salary")
plt.title("Bar chart → Average Salary by Department.")
plt.subplot(1,3,2)
Pie_chart=df["City"].value_counts()
plt.pie(Pie_chart,labels=Pie_chart.index,autopct="%1.1f%%")
plt.title("Pie chart → Employees by City.")
plt.subplot(1,3,3)
Salary=df.groupby("Department")["Salary"].mean()
plt.hist(Salary,bins="auto")
plt.title("Histogram → Salary Distribution.")
plt.tight_layout()
plt.show()
