import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
Number=int(input("Enter the number of SmartPhones :"))
with open("SmartPhones.csv","w") as file:
    writer=csv.writer(file)
    writer.writerow(["Brand","Model","Ram","Storage","Battery","Price"])
    for i in range(Number):
       print("-"*70)
       SmartPhone=str(input(f"Enter the Brand of Smartphone {i+1} : "))
       Model=str(input("Enter the Model of SmartPhone :"))
       Ram=int(input("Enter the Ram of SmartPhone (GB) : "))
       Storage=int(input("Enter the Storage (GB) :"))
       Battery=int(input("Enter the Battery Capacity (mah):"))
       Price=int(input("Enter the Price :"))
       writer.writerow([SmartPhone,Model,Ram,Storage,Battery,Price])
df_csv=pd.read_csv("SmartPhones.csv")
print("-"*70)
print("SmartPhones Having Ram more than 8 GB :")
print(df_csv[df_csv["Ram"] > 8])
print("-"*70)
print("SmartPhones with Price less than 30,000")
print(df_csv[df_csv["Price"] < 30000])
print("-"*70)
print("SmartPhone Having Highest Battery Capacity :")
print(df_csv[df_csv["Battery"]==df_csv["Battery"].max()])
print("-"*70)
print("Average Price  :")
print(df_csv["Price"].mean())
plt.figure(figsize=(8,6))
plt.subplot(2,2,1)
plt.bar(df_csv["Brand"],df_csv["Price"])
plt.xlabel("Brand")
plt.ylabel("Price")
plt.title("Bar Chart → Brand Price")
plt.grid(True)
plt.subplot(2,2,2)
plt.plot(df_csv["Ram"],df_csv["Price"],linestyle=" ",marker="o")
plt.xlabel("Ram")
plt.ylabel("Price")
plt.title("Scatter Plot → RAM vs Price.")
plt.grid(True)
plt.subplot(2,2,3)
plt.hist(df_csv["Battery"],bins="auto",)
plt.title("Histogram → Battery Capacity.")
plt.xlabel("Capacity Of Battery")
plt.grid(True)
plt.pie(df_csv["Quantity"],label=df_csv["Product"],autopct='%1.f%%')
plt.tight_layout()
plt.show()