import numpy as np
Book_Id=np.arange(1001,1101)
print("-"*50)
print("Displaying The Book_Id Array  :")
print(Book_Id)
print("-"*50)
New_Book_Id=Book_Id.reshape(10,10)
print("Displaying The New_Book_Id Array  :")
print(New_Book_Id)
print("-"*50)
print("Displaying Alternative Rows :")
print(New_Book_Id[::2])
print("-"*50)
print("Displaying Alternative colums :")
print(New_Book_Id[:,::2])
print("-"*50)
print("Flatten The Matrix :")
print(New_Book_Id.flatten())

