import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
Number=int(input("Enter the number of flights :"))
with open("Flights_Tickets.csv","w") as file:
    writer=csv.writer(file)
    writer.writerow(["Flight Number","Source","Destination","Ticket Price","Seats Available"])
    for i in range(Number):
       print("-"*70)
       Flight_Number=int(input(f"Enter the Flight Number  of Flight {i+1} : "))
       Source=str(input("Enter the source of Flight :"))
       Destination=str(input("Enter the destination of Flight : "))
       Ticket_Price=int(input("Enter the Ticket Price :"))
       Seats_Available=int(input("Enter the Seats Available :"))
       writer.writerow([Flight_Number,Source,Destination,Ticket_Price,Seats_Available])
df_csv=pd.read_csv("Flights_Tickets.csv")
print("-"*70)
print("Flights costing more than ₹7000 :")
print(df_csv[df_csv["Ticket Price"] > 7000])
print("-"*70)
print("Flights with seats less than 25")
print(df_csv[df_csv["Seats Available"] < 25])
print("-"*70)
print("Highest ticket  :")
print(df_csv[df_csv["Ticket Price"]==df_csv["Ticket Price"].max()])
print("-"*70)
print("Lowest ticket  :")
print(df_csv[df_csv["Ticket Price"]==df_csv["Ticket Price"].min()])
print("-"*70)
print("Average ticket  :")
print(df_csv["Ticket Price"].mean())
plt.figure(figsize=(8,6))
plt.subplot(1,2,1)
plt.bar(df_csv["Flight Number"],df_csv["Ticket Price"])
plt.xlabel("Flight Number")
plt.ylabel("Ticket Price")
plt.title("Bar Chart → Ticket Price")
plt.grid(True)
plt.subplot(1,2,2)
plt.pie(df_csv["Seats Available"],labels=df_csv["Destination"],autopct='%1.1f%%')
plt.title("Destination distribution Seats")
plt.tight_layout()
plt.show()