Student_Name=input("Enter Student Name :")
Roll_Number=input("Enter Roll Number :")
English_Marks=float(input("Enter English Marks :"))
Math_Marks=float(input("Enter Math Marks :"))
Science_Marks=float(input("Enter Science Marks :"))
Computer_Marks=float(input("Enter Computer Marks :"))
Total_Marks=English_Marks+Math_Marks+Science_Marks+Computer_Marks
Percentage=(Total_Marks/400)*100
print("\n=================================")
print("        STUDENT RESULT")
print("=================================\n")
print("Name        : ", Student_Name)
print("Roll Number : ", Roll_Number)
print("\nEnglish     : ", English_Marks)
print("Math        : ", Math_Marks)
print("Science     : ", Science_Marks)
print("Computer    : ", Computer_Marks)
print("\n---------------------------------")
print("Total Marks : ", Total_Marks)
print("Percentage  : ", Percentage,"%")
print("=================================")
