import numpy as np
Number=np.arange(1,37)
print("-"*50)
print("The Array is : \n")
print(Number)
print("-"*50)
print("The Array After Reshaping is : \n")
New_Numbers=Number.reshape(6,6)
print(New_Numbers)
print("-"*50)
print(f"The Dimension of New Array is : {New_Numbers.ndim}\n")
print("-"*50)
print(f"The Size of New Array is : {New_Numbers.size}\n")
print("-"*50)
print(f"The Shape of New Array is : {New_Numbers.shape}\n")